### ISSUE TITLE
ALERTE SUPPRESSION !

### ISSUE THREAD

**Issue by Tha1n** [Tha1n/ESIR2#1]
Plusieurs dossiers ont été supprimés !
Genre tous les TPs de système ont disparu, une partie des TP d'IR (Kévin et moi)
Notre FD a PH et moi
Et des TPs sont manquants dans le dossier de TL

**Comment by Tha1n** [comment]
Comment qu'on récupère tout ça ? :'(

**Comment by AmarOk1412** [comment]
2 moyens. Faire mumuse avec git checkout. Et revenir à une version qui marche (merci git). Donc avant f0f6f55872fe9118c392a6f67436c728db6595ce

Soit je fais une copie de mon git local que je push (ce que j'ai fait). Ça m'a permis d'enlver quelques meta-data btw. Par contre, faut que tu repush ce que tu voulais push à la base

**Comment by Tha1n** [comment]
Tout à l'air d'être la avec ton push.
J'avais rien à push, c'est juste que je cherchais un modèle de CR pour le réseau et c'est la que j'ai vu qu'il manquait un bon paquet de dossiers ><

**Comment by AmarOk1412** [comment]
Nop, c'est le commit TP89 qui a foutu la merde. Du coup manque TP89, merge et prise de note TP6 (trop de modifs : https://github.com/Tha1n/ESIR2/commit/f0f6f55872fe9118c392a6f67436c728db6595ce)

**Comment by AmarOk1412** [comment]
Note, tu auras une belle courbe d'additions :D

**Comment by Tha1n** [comment]
Prise de note a l'air présent.
Et tant pis pour TP89, c'est sur les PCs de l'ESIR.
